---
defaults: &shared_defaults
  player: 2
  runs: 5
  horizon: 200
  seed: 43
  save_folder: "Figures/Test_Pickle_interrupt_2Players"

games:
#  game1:
#    <<: *shared_defaults
#    name: "PG_WP"
#    matrix:
#      - [1, 0.2, 0]
#      - [0.2, 0.8, 0.2]
#      - [0, 0.2, 1]
#    noise:
#      - [0.0, 0.0]
#    algos: ["UCB", "UCB", "UCB"]
#  game2:
#    <<: *shared_defaults
#    name: "PG_WP"
#    matrix:
#      - [1, 0.2, 0]
#      - [0.2, 0.8, 0.2]
#      - [0, 0.2, 1]
#    noise:
#      - [0.0, 0.1]
#    algos: ["UCB", "UCB", "UCB"]
#  game3:
#    <<: *shared_defaults
#    name: "PG_WP"
#    matrix:
#      - [1, 0.2, 0]
#      - [0.2, 0.8, 0.2]
#      - [0, 0.2, 1]
#    noise:
#      - [0.0, 1.0]
#    algos: ["UCB", "UCB", "UCB"]
#  game4:
#    <<: *shared_defaults
#    name: "PG_WP"
#    matrix:
#      - [1, 0.2, 0]
#      - [0.2, 0.8, 0.2]
#      - [0, 0.2, 1]
#    noise:
#      - [0.0, 0.0]
#    algos: ["KLUCB", "KLUCB", "UCB"]
#  game5:
#    <<: *shared_defaults
#    name: "PG_WP"
#    matrix:
#      - [1, 0.2, 0]
#      - [0.2, 0.8, 0.2]
#      - [0, 0.2, 1]
#    noise:
#      - [0.0, 0.1]
#    algos: ["KLUCB", "KLUCB", "UCB"]
#  game6:
#    <<: *shared_defaults
#    name: "PG_WP"
#    matrix:
#      - [1, 0.2, 0]
#      - [0.2, 0.8, 0.2]
#      - [0, 0.2, 1]
#    noise:
#      - [0.0, 1.0]
#    algos: ["KLUCB", "KLUCB", "UCB"]
#  game7:
#    <<: *shared_defaults
#    name: "PG_WP"
#    matrix:
#      - [1, 0.2, 0]
#      - [0.2, 0.8, 0.2]
#      - [0, 0.2, 1]
#    noise:
#      - [0.0, 0.0]
#    algos: ["UCB", "KLUCB", "UCB"]
#  game8:
#    <<: *shared_defaults
#    name: "PG_WP"
#    matrix:
#      - [1, 0.2, 0]
#      - [0.2, 0.8, 0.2]
#      - [0, 0.2, 1]
#    noise:
#      - [0.0, 0.1]
#    algos: [ "UCB", "KLUCB", "UCB"]
#  game9:
#    <<: *shared_defaults
#    name: "PG_WP"
#    matrix:
#      - [1, 0.2, 0]
#      - [0.2, 0.8, 0.2]
#      - [0, 0.2, 1]
#    noise:
#      - [0.0, 1.0]
#    algos: [ "UCB", "KLUCB", "UCB"]
#  game10:
#    <<: *shared_defaults
#    name: "PG_WP"
#    matrix:
#      - [1, 0.2, 0]
#      - [0.2, 0.8, 0.2]
#      - [0, 0.2, 1]
#    noise:
#      - [0.0, 0.0]
#    algos: [ "UCB", "TS", "UCB"]
#  game11:
#    <<: *shared_defaults
#    name: "PG_WP"
#    matrix:
#      - [1, 0.2, 0]
#      - [0.2, 0.8, 0.2]
#      - [0, 0.2, 1]
#    noise:
#      - [0.0, 0.1]
#    algos: [ "UCB", "TS", "UCB"]
#  game12:
#    <<: *shared_defaults
#    name: "PG_WP"
#    matrix:
#      - [1, 0.2, 0]
#      - [0.2, 0.8, 0.2]
#      - [0, 0.2, 1]
#    noise:
#      - [0.0, 1.0]
#    algos: [ "UCB", "TS", "UCB"]
#  game13:
#    <<: *shared_defaults
#    name: "PG_WP"
#    matrix:
#      - [1, 0.2, 0]
#      - [0.2, 0.8, 0.2]
#      - [0, 0.2, 1]
#    noise:
#      - [0.0, 0.0]
#    algos: [ "TS", "TS", "UCB"]
#  game14:
#    <<: *shared_defaults
#    name: "PG_WP"
#    matrix:
#      - [1, 0.2, 0]
#      - [0.2, 0.8, 0.2]
#      - [0, 0.2, 1]
#    noise:
#      - [0.0, 0.1]
#    algos: [ "TS", "TS", "UCB"]
#  game15:
#    <<: *shared_defaults
#    name: "PG_WP"
#    matrix:
#      - [1, 0.2, 0]
#      - [0.2, 0.8, 0.2]
#      - [0, 0.2, 1]
#    noise:
#      - [0.0, 1.0]
#    algos: [ "TS", "TS", "UCB"]
  game1:
    <<: *shared_defaults
    name: "PG_WP"
    matrix:
      - [1, 0.2, 0]
      - [0.2, 0.8, 0.2]
      - [0, 0.2, 1]
    noise:
      - [0.0, 0.0]
    algos: ["UCB", "UCB"]
  game2:
    <<: *shared_defaults
    name: "PG_WP"
    matrix:
      - [1, 0.2, 0]
      - [0.2, 0.8, 0.2]
      - [0, 0.2, 1]
    noise:
      - [0.0, 0.1]
    algos: ["UCB", "UCB"]
  game3:
    <<: *shared_defaults
    name: "PG_WP"
    matrix:
      - [1, 0.2, 0]
      - [0.2, 0.8, 0.2]
      - [0, 0.2, 1]
    noise:
      - [0.0, 1.0]
    algos: ["UCB", "UCB"]
  game4:
    <<: *shared_defaults
    name: "PG_WP"
    matrix:
      - [1, 0.2, 0]
      - [0.2, 0.8, 0.2]
      - [0, 0.2, 1]
    noise:
      - [0.0, 0.0]
    algos: ["KLUCB", "KLUCB"]
  game5:
    <<: *shared_defaults
    name: "PG_WP"
    matrix:
      - [1, 0.2, 0]
      - [0.2, 0.8, 0.2]
      - [0, 0.2, 1]
    noise:
      - [0.0, 0.1]
    algos: ["KLUCB", "KLUCB"]
  game6:
    <<: *shared_defaults
    name: "PG_WP"
    matrix:
      - [1, 0.2, 0]
      - [0.2, 0.8, 0.2]
      - [0, 0.2, 1]
    noise:
      - [0.0, 1.0]
    algos: ["KLUCB", "KLUCB"]
  game7:
    <<: *shared_defaults
    name: "PG_WP"
    matrix:
      - [1, 0.2, 0]
      - [0.2, 0.8, 0.2]
      - [0, 0.2, 1]
    noise:
      - [0.0, 0.0]
    algos: ["UCB", "KLUCB"]
  game8:
    <<: *shared_defaults
    name: "PG_WP"
    matrix:
      - [1, 0.2, 0]
      - [0.2, 0.8, 0.2]
      - [0, 0.2, 1]
    noise:
      - [0.0, 0.1]
    algos: [ "UCB", "KLUCB"]
  game9:
    <<: *shared_defaults
    name: "PG_WP"
    matrix:
      - [1, 0.2, 0]
      - [0.2, 0.8, 0.2]
      - [0, 0.2, 1]
    noise:
      - [0.0, 1.0]
    algos: [ "UCB", "KLUCB" ]
  game10:
    <<: *shared_defaults
    name: "PG_WP"
    matrix:
      - [1, 0.2, 0]
      - [0.2, 0.8, 0.2]
      - [0, 0.2, 1]
    noise:
      - [0.0, 0.0]
    algos: [ "UCB", "TS" ]
  game11:
    <<: *shared_defaults
    name: "PG_WP"
    matrix:
      - [1, 0.2, 0]
      - [0.2, 0.8, 0.2]
      - [0, 0.2, 1]
    noise:
      - [0.0, 0.1]
    algos: [ "UCB", "TS" ]
  game12:
    <<: *shared_defaults
    name: "PG_WP"
    matrix:
      - [1, 0.2, 0]
      - [0.2, 0.8, 0.2]
      - [0, 0.2, 1]
    noise:
      - [0.0, 1.0]
    algos: [ "UCB", "TS" ]
  game13:
    <<: *shared_defaults
    name: "PG_WP"
    matrix:
      - [1, 0.2, 0]
      - [0.2, 0.8, 0.2]
      - [0, 0.2, 1]
    noise:
      - [0.0, 0.0]
    algos: [ "TS", "TS" ]
  game14:
    <<: *shared_defaults
    name: "PG_WP"
    matrix:
      - [1, 0.2, 0]
      - [0.2, 0.8, 0.2]
      - [0, 0.2, 1]
    noise:
      - [0.0, 0.1]
    algos: [ "TS", "TS" ]
  game15:
    <<: *shared_defaults
    name: "PG_WP"
    matrix:
      - [1, 0.2, 0]
      - [0.2, 0.8, 0.2]
      - [0, 0.2, 1]
    noise:
      - [0.0, 1.0]
    algos: [ "TS", "TS" ]